#!/bin/sh

# install the default password (admin/admin)
# TODO: make this read default passwords from configuration file
SHADOW_FILE=/etc/orange/shadow

mkdir -p $(dirname $SHADOW_FILE)
rm -f $SHADOW_FILE
which sha1sum || { echo "ERROR: you need to have sha1sum installed for JUCI to work!"; return -1; }
echo "admin `printf root|sha1sum | awk '{printf $1}'`" > $SHADOW_FILE
chmod 700 $SHADOW_FILE


exit 0
