#!/bin/sh /etc/rc.common
# Copyright (C) 2016 OpenWrt.org

# start after and stop before networking
START=99
STOP=89

USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "gmediarender"
}

start_service()
{
	procd_open_instance
	procd_set_param command /usr/sbin/gmediarender -I 192.168.100.1 -f respeaker
	procd_set_param respawn
	procd_close_instance
}
