#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'Mopidy==2.0.1','console_scripts','mopidy'
__requires__ = 'Mopidy==2.0.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Mopidy==2.0.1', 'console_scripts', 'mopidy')()
    )
