#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*linkit$//g" /etc/opkg/distfeeds.conf

wan_mac=$(mtd_get_mac_binary factory 4)

uci set network.wan.macaddr=$wan_mac
uci commit network

uci delete uhttpd.main.alias
uci commit uhttpd
#set uart0 as gpio function
mt7688_pinmux set uart0 gpio
[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

[ "$board" = "linkits7688d" ] || rm /etc/avahi/services/arduino.service


uci set system.@system[-1].hostname="ReSpeaker"
uci set system.@system[0].fasterconfig=1
uci set system.@system[0].version_skip=0

uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || { \
	MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
	SSID=ReSpeaker${MAC}
}
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

[ -n "${KEY}" ] && {
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.key="$KEY"
}

uci set network.wan=interface
uci set network.wan.proto=dhcp
uci set network.wan.ifname=apcli0
uci set network.wan.macaddr=9E:65:F9:0D:81:28
uci set network.lan.ipv6='0'

uci set mountd.mountd.path=/Media/

uci commit
#set uart0 as gpio function
mt7688_pinmux set uart0 gpio
return 0
